title: MERITHA
author: Anna Lam
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Anna Lam is a 2D visual artist, often illustrating under the pseudonym Meritha. Somewhat of a jack of trades, she also creates short animated graphics, designs and codes for front-end web development, and enjoys writing fiction and poetry.

# social links
twitter_username: @MerithaMarrow
github_username:  Meritha

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
